export const REQUEST_START = 'REQUEST_START';
export const REQUEST_FAIL = 'REQUEST_FAIL';
export const RECEIVE_DATA = 'RECEIVE_DATA';

export const TOGGLE_SHOW = 'TOGGLE_SHOW';
export const ADD_FILTER = 'ADD_FILTER';
export const REMOVE_FILTER = 'REMOVE_FILTER';

export const UPDATE_RANGE_FILTER = 'UPDATE_RANGE_FILTER';
